export const FETCH_MOVIES_REQUESTED = 'FETCH_MOVIES_REQUESTED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';

export const FETCH_MOVIE_GENRES_REQUESTED = 'FETCH_MOVIE_GENRES_REQUESTED';
export const FETCH_MOVIE_GENRES_SUCCESS = 'FETCH_MOVIE_GENRES_SUCCESS';
export const FETCH_MOVIE_GENRES_FAILED = 'FETCH_MOVIE_GENRES_FAILED';

export const FETCH_TV_GENRES_REQUESTED = 'FETCH_TV_GENRES_REQUESTED';
export const FETCH_TV_GENRES_SUCCESS = 'FETCH_TV_GENRES_SUCCESS';
export const FETCH_TV_GENRES_FAILED = 'FETCH_TV_GENRES_FAILED';

export const FETCH_TRENDING_REQUESTED = 'FETCH_TRENDING_REQUESTED';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_FAILED = 'FETCH_TRENDING_FAILED';